### ISSUE TITLE
/run/mysqld/mysqld.sock exists

### ISSUE THREAD

**Issue by liuqu11** [mplx/docker-pixelfed#2]
Hi , mplx   
      Thank you for the mirror.

       my operation is

1. docker run --name mysql -p 3306: 3306 -e MYSQL_ROOT_PASSWORD = root -v / cloud / pixelfed / mysql: / var / lib / mysql -d mysql: 5.7

2. docker run -p 6379: 6379 -v / cloud / pixelfed / redis: / data -d --name redis redis: 4-alpine --appendonly yes

3. docker run -d -p 8000: 8000 -e 'DB_DATABASE = pixelfed' -e 'DB_USERNAME = root' -e 'DB_PASSWORD = root' -v / cloud / pixelfed / data: / home / project / pixelfed / storage --rm --name web mplx / docker-pixelfed: master

than show me 

#docker logs web
Pixelfed v0.10.9 entrypoint
mysqladmin: connect to server at '127.0.0.1' failed
error: 'Can't connect to MySQL server on '127.0.0.1' (115)'
Check that mysqld is running and that the socket: '/run/mysqld/mysqld.sock' exists!
Waiting for mysql database...
mysqladmin: connect to server at '127.0.0.1' failed
error: 'Can't connect to MySQL server on '127.0.0.1' (115)'
Check that mysqld is running and that the socket: '/run/mysqld/mysqld.sock' exists!

please help me

**Comment by mplx** [comment]
1) To set a pixelfed database host you'll need to define it; while pixelfed itself [defaults to 127.0.0.1](https://docs.pixelfed.org/technical-documentation/env.html#database-configuration) this isn't suitable in a docker environment so you'll need to define the environment variable 'DB_HOST'.

2) If you run multiple docker containers depending on each other you'll have to connect them via user-defined networks or the (legacy) `--link` parameter - see https://docs.docker.com/network/links/. I strongly suggest to use [docker compose](https://docs.docker.com/compose/) instead of running 3 containers separately.

**Comment by liuqu11** [comment]
I can run the following script to execute

`
version: '3.7'

services:
  web:
    image: mplx/docker-pixelfed:master
    ports:
    - "80:8000"
    env_file:
      - ./pixelfed.env
    volumes:
      - /cloud/pixelfed/data:/home/project/pixelfed/storage
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    ports:
    - "3306:3306"
    env_file: ./mysql.env
    volumes:
      - /cloud/pixelfed/mysql:/var/lib/mysql
  redis:
    image: redis:4-alpine
    ports:
    - "6379:6379"
    volumes:
      - /cloud/pixelfed/redis:/data

`



But I still have some doubts. I ran the program. Only the login interface was not registered. Is there any setting?
